### ISSUE TITLE
多节点部署问题

### ISSUE THREAD

**Issue by jingslunt** [nick-zh/docker-kafka-eagle#14]
多节点(swarm)我是这么部署的，如果要加入eagle,需要怎么配置 
> docker stack deploy -c docker-compose.yml swarm --resolve-image=never --with-registry-auth #部署命令
```
version: '3.4'

services:
  zk-1: &zk
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - zk-common.env
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    volumes:
      - zk-1:/var/lib/zookeeper/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-01]
  zk-2:
    <<: *zk
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zk-1:2888:3888;0.0.0.0:2888:3888;zk-3:2888:3888
    volumes:
      - zk-2:/var/lib/zookeeper/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-02]
  zk-3:
    <<: *zk
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zk-1:2888:3888;zk-2:2888:3888;0.0.0.0:2888:3888
    volumes:
      - zk-3:/var/lib/zookeeper/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-03]
  kafka-1: &kafka
    image: confluentinc/cp-kafka:latest
    env_file:
      - kafka-common.env
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9192,EXTERNAL://localhost:9092
      KAFKA_JMX_HOSTNAME: kafka-1
    ports:
      - 9092:9092
    volumes:
      - kafka-1:/var/lib/kafka/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-01]
  kafka-2:
    <<: *kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9192,EXTERNAL://localhost:9093
      KAFKA_JMX_HOSTNAME: kafka-2
    ports:
      - 9093:9092
    volumes:
      - kafka-2:/var/lib/kafka/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-02]
  kafka-3:
    <<: *kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9192,EXTERNAL://localhost:9094
      KAFKA_JMX_HOSTNAME: kafka-3
    ports:
      - 9094:9092
    volumes:
      - kafka-3:/var/lib/kafka/data
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-03]
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: zk-1:2181,zk-2:2181,zk-3:2181
      JMX_PORT: 9181
      APPLICATION_SECRET: letmein
    ports:
      - 9000:9000
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-01]

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == kafka-01-01]

volumes:
  zk-1:
  zk-2:
  zk-3:
  kafka-1:
  kafka-2:
  kafka-3:
#   name: kafka #可自定义存储名

```
